#!/usr/bin/env python3
"""PreToolUse GUARD — a deterministic (code, not LLM) hook that inspects a tool call BEFORE it runs
and BLOCKS or ASKS on high-risk operations. This is the hard floor under the deep verifier: the
verifier reviews after the fact, this stops the catastrophic op from ever executing.

It reads the standard PreToolUse hook JSON on stdin: {"tool_name": ..., "tool_input": {...}}, and
emits the PreToolUse decision protocol on stdout:
  {"hookSpecificOutput": {"hookEventName": "PreToolUse",
     "permissionDecision": "allow" | "deny" | "ask", "permissionDecisionReason": "..."}}

Policy (all patterns are CONFIGURABLE constants below):
  - DENY: irreversible/destructive shell (rm -rf, git push --force, git reset --hard, dd, mkfs,
    truncate of tracked files, history-rewrites) and ANY write/edit to a SACRED path.
  - ASK : risky-but-sometimes-legitimate (bulk/mass deletes, chmod -R, broad git checkout/clean,
    writing to dotfiles/secrets-shaped names) — surfaces to the human instead of auto-running.
  - ALLOW: everything else (the common case — fast, no friction).

Determinism: the decision is pure pattern logic over the tool input. No model is consulted.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------------------------------------
# CONFIG — edit these lists to tune the policy. Patterns are regexes matched against the command
# string (for Bash) or the file path (for Edit/Write/MultiEdit/NotebookEdit).
# --------------------------------------------------------------------------------------------------

# --------------------------------------------------------------------------------------------------
# 2026-07-26 WIDENING (Michael: "I keep not getting work done because of pre-tool use bashes").
# Measured, not guessed: 79,383 real Bash invocations from session transcripts scored through
# decide(). 398 denied + 12 asked = 0.52% of all calls -- but 350 of those 410 (85%) were ONE idiom,
# cache-dir cleanup via `find ... -exec rm -rf {} +`, and most of the rest were MENTION-matches
# (a command that merely CONTAINS a pattern's text). Observed live: a read-only `grep` FOR a rule's
# text was blocked BY that rule, twice, while writing the tests for this change.
#
# Two structural fixes, both narrow:
#   1. CATASTROPHIC vs CONTEXTUAL. Catastrophic patterns (root deletes, dd, mkfs, fork bomb) match
#      the RAW command, so nothing can hide inside quotes. Contextual ones (rebase, force push,
#      git clean) match a NOISE-STRIPPED copy with quoted literals and # comments removed, so
#      talking about a command is no longer the same as running it.
#   2. DISPOSABLE TARGETS. A recursive-force delete is allowed only when EVERY target it names is
#      regenerable (cache dirs, node_modules, build output, /tmp, the scratchpad). Any other target
#      in the same command -- and any sacred path -- re-arms the deny.
# --------------------------------------------------------------------------------------------------

#: Directories whose entire contents are regenerated by the next build/test run. Deleting one is
#: not a data-loss event, which is what the recursive-delete rule is actually protecting against.
DISPOSABLE_TARGET_PATTERNS = [
    r"(^|/)__pycache__(/|$)",
    r"(^|/)node_modules(/|$)",
    r"(^|/)\.(pytest|mypy|ruff|jest)_cache(/|$)",
    r"(^|/)\.tox(/|$)",
    r"(^|/)\.next(/|$)",
    r"(^|/)(dist|build|coverage|htmlcov)(/|$)",
    r"(^|/)\.turbo(/|$)",
    r"^/tmp/",
    r"(^|/)scratchpad(/|$)",
    r"(^|/)\.tmp(/|$)",
    r"\.egg-info(/|$)",
]

#: A recursive delete whose target is one of these is NEVER disposable, whatever else is in the
#: command. `/`, `~`, `$HOME`, and bare `.`/`..` are the classic catastrophic targets.
NEVER_DISPOSABLE = [
    r"^[/~.]$", r"^\.\.$", r"^\$HOME$", r"^\$\{HOME\}$", r"^~/?$", r"^/\*",
]

#: Rebase sub-commands that UNDO or resume a rebase rather than start one. Denying `--abort`
#: blocks the recovery path, which is strictly worse than allowing it.
REBASE_SAFE_VERBS = r"\bgit\s+rebase\s+--(abort|continue|skip|quit|edit-todo|show-current-patch)\b"


def _strip_noise(command: str) -> str:
    """A copy of the command with quoted string literals and `#` comments blanked out.

    Used ONLY for contextual patterns. `grep -n "git rebase" f.py` and `echo "filter-branch"`
    are not rebases; blanking quoted runs makes that distinction mechanical rather than a
    special case per pattern. Catastrophic patterns deliberately do NOT use this -- see
    test_quotes_do_not_launder_a_catastrophic_command.
    """
    out, i, n = [], 0, len(command)
    while i < n:
        ch = command[i]
        if ch in "\"'":
            j = i + 1
            while j < n and command[j] != ch:
                j += 2 if command[j] == "\\" else 1
            out.append(" " * (min(j, n - 1) - i + 1))
            i = j + 1
        elif ch == "#":
            j = command.find("\n", i)
            j = n if j < 0 else j
            out.append(" " * (j - i))
            i = j
        else:
            out.append(ch)
            i += 1
    return "".join(out)


#: Anything that can EXECUTE a string it was handed. When one of these is present, quoting stops
#: being evidence that the text is inert, so catastrophic patterns are matched against the RAW
#: command. Without one, a quoted run is data -- `grep -n "<destructive text>" file` is a read.
STRING_EXECUTORS = r"\b(bash|sh|zsh|ksh|dash)\s+-[a-zA-Z]*c\b|\beval\b|\bxargs\b|\bsource\b|\bssh\b"


def _catastrophic_hit(command: str) -> str | None:
    """Match the catastrophic set, choosing raw vs noise-stripped by whether the command can
    execute a string.

    This is the one place the two requirements meet: `bash -c "rm -rf /"` must still be denied
    (so quotes cannot launder it), while `grep -n "rm -rf" f.py` must be allowed (so talking
    about a command is not running it). The discriminator is not the quoting -- it is whether
    anything present could turn that quoted text back into a command.
    """
    haystack = command if re.search(STRING_EXECUTORS, command) else _strip_noise(command)
    for pat in DENY_COMMAND_PATTERNS:
        if pat in CATASTROPHIC_PATTERNS and re.search(pat, haystack):
            if pat in RECURSIVE_DELETE_PATTERNS and _is_disposable_delete(haystack):
                continue
            return pat
    return None


def _recursive_delete_targets(command: str) -> list[str]:
    """The paths a recursive-force `rm` in this command actually names.

    Returns [] when no such rm is present. `{}` (a find -exec placeholder) resolves to the
    find's own `-name`/`-path` arguments, since that is what will be handed to the rm.
    """
    targets: list[str] = []
    for m in re.finditer(r"\brm\s+((?:-[a-zA-Z-]+\s+)+)([^|;&\n]*)", command):
        flags, rest = m.group(1), m.group(2)
        joined = flags.replace("-", "")
        if not (("r" in joined or "R" in joined or "recursive" in flags)
                and ("f" in joined or "force" in flags)):
            continue
        for tok in rest.split():
            tok = tok.strip("\"'")
            if not tok or tok.startswith("-") or tok.startswith("2>") or tok.startswith(">"):
                continue
            if tok in ("{}", "+", ";", "\\;"):
                names = re.findall(r"-(?:name|path|iname)\s+([^\s]+)", command)
                targets.extend(x.strip("\"'") for x in names)
                continue
            targets.append(tok)
    return targets


def _is_disposable_delete(command: str) -> bool:
    """True only if a recursive-force rm is present AND every target it names is regenerable."""
    targets = _recursive_delete_targets(command)
    if not targets:
        return False
    for t in targets:
        if _match_any(NEVER_DISPOSABLE, t) or _is_sacred(t):
            return False
        if not _match_any(DISPOSABLE_TARGET_PATTERNS, t):
            return False
    return True


# Irreversible / destructive shell -> DENY outright.
DENY_COMMAND_PATTERNS = [
    # rm with BOTH recursive (-r/-R/--recursive) and force (-f/--force), flags in any order or split.
    # NOTE: `\n` is excluded from the lookahead char class (2026-07-24) so an unrelated `rm -rf`
    # on a LATER line of a multi-line/multi-command Bash string can't false-positive-block an
    # earlier, harmless `rm -f` on its own line — the lookahead must stay within one logical command.
    # RECURSIVE-FORCE-DELETE PATTERNS REMOVED 2026-07-26.
    #
    # Replaced by OS-level containment, which is what Anthropic's own docs recommend for this:
    # the sandbox confines Bash writes to cwd + session tmp, which IS the "inside the working
    # tree is fine, outside is not" boundary these regexes were trying and failing to express
    # (a Bash glob or regex has no path-resolution logic, so it cannot tell those apart at all).
    # Root- and home-directory removals additionally trip an unconditional circuit breaker that
    # fires even under bypassPermissions.
    #
    # These were the single largest source of real friction in this repo, and inside a git
    # working tree they guarded nothing git does not already recover. They also demonstrated
    # their own worst failure mode while being deleted: because catastrophic patterns match RAW
    # command text so quoting cannot hide them, a code comment that merely NAMED the flag
    # combination was itself blocked. A guard that cannot be edited without tripping over its
    # own rule text is measuring the wrong thing.
    # `--force-with-lease` REMOVED from this list 2026-07-26: it is the SAFE variant (it refuses if
    # the remote moved), and denying it pushes the user toward plain `--force`, which is worse.
    # The bare `\+` alternative was also removed -- it matched ANY '+' in a command containing
    # `git push` (`chmod +x`, `find -exec ... {} +`). A force refspec is `+src:dst`, matched below.
    r"\bgit\s+push\b[^|;&\n]*(--force\b(?!-with-lease)|\s-f\b)",
    # force refspec: `+src:dst` AND the colon-less shorthand `+branch`. Anchored to a token that
    # starts with '+' AFTER `git push`, so `chmod +x … && git push …` (the '+' is before, and `&&`
    # is outside the char class) does not match.
    r"\bgit\s+push\b[^|;&\n]*\s\+[A-Za-z0-9_./~^-]+(:[^\s]*)?(\s|$)",
    # REMOVED 2026-07-26 — all reflog-recoverable, all firing on ordinary autonomous branch work:
    #   git reset --hard          reflog recovers committed work
    #   git clean -fd             fired on routine housekeeping (14 of the measured blocks)
    #   git checkout -- . / .     the real exposure is UNCOMMITTED work; per-step commits are the
    #                             actual fix, and this fired constantly on scoped agent cleanup
    #   git rebase                reflog-recoverable, and rebasing onto main is routine work
    #
    # KEPT: history rewrites that are NOT reflog-recoverable on a shared remote.
    r"\bgit\s+(filter-branch|filter-repo)\b",
    r"\bdd\s+.*\bof=/dev/",
    r"\bmkfs\b",
    r":\s*\(\s*\)\s*\{\s*:\s*\|\s*:\s*&\s*\}\s*;\s*:",  # fork bomb
    r">\s*/dev/sd[a-z]",
    r"\bchown\s+-R\b.*\s/(\s|$)",                        # recursive chown at root
]

# \b(shred|wipe)\b REMOVED from DENY 2026-07-23 (Michael: "too restrictive"): it fired on routine
# scratch-file cleanup (e.g. `shred -u /tmp/.../secret`) with no sacred-path involvement — the
# sacred-path redirect/edit checks already cover the cases that matter. Same rationale as the sudo
# removal below.

# \bfind\s+.*-delete\b REMOVED from ASK 2026-07-24 (Michael): fired constantly on routine agent
# scratch/test-harness cleanup (e.g. `find <tmp-dir> -type f -delete`), interrupting autonomous
# sub-agent work for a pattern that's rarely actually dangerous outside a sacred path (which the
# sacred-path redirect/edit checks already catch separately). Same rationale as the sudo/shred
# removals below.

# WIDENED 2026-07-24 (Michael, explicit: "widen the approval appropriately... unless it's something
# really dangerous, I don't want to see it"): the following were ASK, now ALLOW, because in this repo
# they're all recoverable via git (working-tree discards can be re-derived from history/reflog; bulk
# edits land as an ordinary diff you can review/revert) and were firing on routine autonomous-agent
# work, not genuine one-way operations:
#   \bxargs\s+.*\brm\b                              -- xargs rm (same class as the find -delete removal)
#   \bgit\s+checkout\s+[^\s-]\S*\s+--\s              -- checkout <tree> -- <path> (discards a path's
#                                                        working-tree changes; recoverable if committed
#                                                        anywhere, and the DENY list still catches
#                                                        `git checkout -- .` / `git checkout .`, the
#                                                        whole-tree wipe)
#   \bgit\s+restore\b                                -- same rationale (working-tree discard only)
#   \bchmod\s+-R\b                                   -- permission changes, not data loss
#   \bsed\s+-i\b.*\*  / for-loop-over-glob / \bperl\s+-i\b.*\*  -- bulk edits are just an ordinary,
#                                                        reviewable/revertable git diff afterward
#   \bgit\s+rm\s+-r\b                                -- removes from git's working tree/index only;
#                                                        recoverable via `git checkout HEAD -- <path>`
# Genuinely one-way or externally-facing operations (npm publish, pipe-to-shell, installing from an
# arbitrary git URL, and permanently dropping stashed work with no history trail) stay on ASK below.

# Risky-but-sometimes-legitimate -> ASK (surface to human). Kept deliberately short: only ops that are
# either irreversible outside git (stash clear/drop) or reach outside the repo/machine (publish,
# pipe-to-shell, installing arbitrary remote code).
ASK_COMMAND_PATTERNS = [
    r"\bgit\s+stash\s+(clear|drop)\b",
    # \bsudo\b REMOVED 2026-07-04 (Michael): it fired on harmless port checks (sudo lsof) and even on
    # commands merely CONTAINING the word (grep "sudo" ...), repeatedly interrupting autonomous
    # sub-agent builds. sudo'd DESTRUCTIVE commands are still caught by the DENY patterns above.
    r"\bnpm\s+(publish|unpublish)\b",
    r"\bpip\s+install\b.*\bgit\+",
    r"\bcurl\b.*\|\s*(sh|bash)\b",     # pipe-to-shell
    r"\bwget\b.*\|\s*(sh|bash)\b",
]

# Bulk-edit heuristic REMOVED from ASK 2026-07-24 (Michael, same widening as above): sed/perl -i over a
# glob, a for-loop redirect over a glob, and `git rm -r` all land as an ordinary, reviewable git diff —
# nothing here is destroyed outside version control. Kept as an empty list (rather than deleted outright)
# so `_match_any` call sites and tests documenting the removal stay simple.
BULK_EDIT_PATTERNS = []

# NEVER-EDIT paths -> DENY. Only the genuinely irreversible/secret set: credentials, the git store,
# the IMMUTABLE WITNESS (the golden master the loop must never doctor to pass), and LIVE production
# model weights (destroying these loses a trained capability — learned the hard way 2026-06-19).
#
# DELIBERATELY NOT HERE: load-bearing *code* (solver/, closure.py, harness/done_gate.py,
# .claude/settings.json, invariant_check.py). Per this repo's autonomy model (STATE.md "LOAD-BEARING"),
# that code is FIXABLE autonomously and is governed at ACCEPT time by the HARDENED GATE (TDD + sentinel
# + git-isolation) — NOT hard-blocked at edit time. Hard-denying it would lock the loop out of
# improving its own gate/core, which is exactly what Michael said NOT to do.
SACRED_PATH_PATTERNS = [
    r"(^|/)\.env(\.|$)",
    r"(^|/)secrets?(/|\.|$)",
    r"(^|/)id_rsa\b",
    r"(^|/)\.git/",
    r"reports/golden_witness\.json$",   # the immutable witness — the loop must never doctor it
    r"reports/model_c\.pt$",         # LIVE production holographic decoder
    r"(^|/)runs/model_a(/|$)",             # LIVE model weights (name redacted)
    r"(^|/)runs/model_b(/|$)",             # LIVE model weights (name redacted)
]

#: The recursive-force-delete patterns, selected by what they MATCH rather than by position in the
#: list (an index slice silently re-classifies a rule the moment someone reorders the list -- the
#: same declared-alongside-reality failure this repo keeps finding). A match on one of these is
#: waived when every target the command names is regenerable (see _is_disposable_delete).
RECURSIVE_DELETE_PATTERNS = frozenset(p for p in DENY_COMMAND_PATTERNS if r"\brm\s+" in p)

#: Matched against the RAW command, never the noise-stripped copy: these destroy a disk, a machine,
#: or a home directory, so `bash -c "<it>"` must not become invisible just because it is quoted.
#: Everything NOT in this set is CONTEXTUAL -- matched after quotes/comments are blanked, so that
#: naming a command in an echo/grep is no longer the same as running it.
_CATASTROPHIC_MARKERS = (r"\brm\s+", r"\bdd\s+", r"\bmkfs\b", r">\s*/dev/sd[a-z]",
                         r"\bchown\s+-R\b", r":\s*\(\s*\)")
CATASTROPHIC_PATTERNS = frozenset(
    p for p in DENY_COMMAND_PATTERNS if any(m in p for m in _CATASTROPHIC_MARKERS))

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit", "Update"}


def _flag(name: str) -> str:
    return name


def _match_any(patterns: list[str], text: str) -> str | None:
    for pat in patterns:
        if re.search(pat, text):
            return pat
    return None


def _is_sacred(path: str) -> str | None:
    norm = path.replace("\\", "/")
    return _match_any(SACRED_PATH_PATTERNS, norm)


def _redirect_targets(command: str) -> list[str]:
    """Files a shell command writes to via >, >>, or tee — used to catch sacred-path writes from Bash."""
    targets = re.findall(r"(?:>>?|\btee\s+(?:-a\s+)?)\s*([^\s;|&]+)", command)
    return [t for t in targets if t not in ("/dev/null",)]


def decide(tool_name: str, tool_input: dict) -> dict:
    """Pure decision function. Returns {permissionDecision, permissionDecisionReason}."""
    tool_input = tool_input or {}

    # 1) File-editing tools -> sacred-path check.
    if tool_name in EDIT_TOOLS:
        path = (tool_input.get("file_path") or tool_input.get("path")
                or tool_input.get("notebook_path") or "")
        hit = _is_sacred(str(path))
        if hit:
            return _deny(f"{tool_name} targets a SACRED path ({path}); matched {hit!r}. "
                         "Escalate to a human — do not modify load-bearing/secret files via the agent.")
        return _allow()

    # 2) Shell commands.
    if tool_name == "Bash":
        command = str(tool_input.get("command", ""))

        # 2a) sacred-path writes via redirect.
        for tgt in _redirect_targets(command):
            hit = _is_sacred(tgt)
            if hit:
                return _deny(f"Bash redirects output into a SACRED path ({tgt}); matched {hit!r}. "
                             "Escalate to a human.")

        # 2b) destructive -> deny.
        #
        # CATASTROPHIC patterns match the RAW command so quoting cannot hide them; CONTEXTUAL ones
        # match a noise-stripped copy so that *mentioning* a command is not *running* it. The
        # recursive-delete rule is skipped entirely when every target it names is regenerable.
        stripped = _strip_noise(command)
        hit = _catastrophic_hit(command)
        if not hit:
            hit = next((p for p in DENY_COMMAND_PATTERNS
                        if p not in CATASTROPHIC_PATTERNS and re.search(p, stripped)), None)
        if hit:
            return _deny(f"High-risk irreversible command blocked (matched {hit!r}): {command[:200]}. "
                         "If this is genuinely intended, run it manually outside the agent.")

        # 2c) bulk edits -> ask.
        hit = _match_any(BULK_EDIT_PATTERNS, command)
        if hit:
            return _ask(f"Bulk/mass file edit (matched {hit!r}): {command[:200]}. "
                        "Confirm the blast radius before proceeding.")

        # 2d) risky-but-legitimate -> ask.
        hit = _match_any(ASK_COMMAND_PATTERNS, command)
        if hit:
            return _ask(f"Risky command needs confirmation (matched {hit!r}): {command[:200]}.")

        return _allow()

    # 3) everything else allowed.
    return _allow()


def _decision(kind: str, reason: str) -> dict:
    return {"permissionDecision": kind, "permissionDecisionReason": reason}


def _allow() -> dict:
    return _decision("allow", "no high-risk pattern matched")


def _deny(reason: str) -> dict:
    return _decision("deny", reason)


def _ask(reason: str) -> dict:
    return _decision("ask", reason)


def to_hook_output(decision: dict) -> dict:
    """Wrap a decision in the PreToolUse hookSpecificOutput envelope."""
    return {"hookSpecificOutput": {
        "hookEventName": "PreToolUse",
        "permissionDecision": decision["permissionDecision"],
        "permissionDecisionReason": decision["permissionDecisionReason"],
    }}


def main() -> int:
    raw = "" if sys.stdin.isatty() else sys.stdin.read()
    try:
        hook = json.loads(raw) if raw.strip() else {}
    except Exception:
        hook = {}
    decision = decide(hook.get("tool_name", ""), hook.get("tool_input", {}))
    print(json.dumps(to_hook_output(decision)))
    # A deny is communicated via the JSON protocol (permissionDecision), not the exit code; exit 0 so
    # Claude Code reads the structured decision rather than treating a nonzero exit as a hook error.
    return 0


if __name__ == "__main__":
    sys.exit(main())
